import type { Metadata } from "next";
import "../styles/globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";

export const metadata: Metadata = {
  title: {
    template: "%s - Diana Imóveis",
    default: "Diana Imóveis - Descubra seu novo Lar!",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
