import type { Metadata } from "next";
import ReactQueryProvider from "@/providers/react-query-provider";
import "../styles/globals.css";
import { Playfair_Display, Inter } from "next/font/google";

const playfair_display = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-primary",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: {
    template: "%s - Diana Imóveis",
    default: "Diana Imóveis - Descubra seu novo Lar!",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${inter.variable} ${playfair_display.variable}`}
    >
      <body className="antialiased">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
