import type { Metadata } from "next";
import { Geist, Poppins } from "next/font/google";
import "../styles/globals.css";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    template: "%s - Diana Imóveis",
    default: "Diana Imóveis - Descubra seu novo Lar!",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.className} ${geistSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
